version: '3.7'

services:
  geth-bootnode:
    hostname: geth-bootnode
    env_file:
      - .env
    image: geth-client
    build:
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    command:
      --nodekeyhex="1b61dd74b5e59f7f47e6618664513a5d65813712cdcb67c78717a7e7f421f7bf"
      --nodiscover
      --ipcdisable
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
      --port=${NETWORK_PORT}
    networks:
      priv-eth-net:

  geth-rpc-endpoint:
    hostname: geth-rpc-endpoint
    env_file:
      - .env
    image: geth-client
    build:
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    depends_on:
      - geth-bootnode    
    command:
      --bootnodes="enode://3506195bad0d414294a2d8dee98858619f002e77ea97f095ccdc4b461ce26176a13330fbb195a268b283ff7a67939f84da59d5920ff53f9a7b200613297607f6@geth-bootnode:${NETWORK_PORT}"
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,txpool,clique,personal"
      --http.corsdomain="*"
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
      # --authrpc.port="8551"
    ports:
      - "8545:8545"
    networks:
      priv-eth-net:

  geth-miner:
    hostname: geth-miner
    env_file:
      - .env
    image: geth-client
    build:
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://3506195bad0d414294a2d8dee98858619f002e77ea97f095ccdc4b461ce26176a13330fbb195a268b283ff7a67939f84da59d5920ff53f9a7b200613297607f6@geth-bootnode:${NETWORK_PORT}"
      --mine
      --miner.etherbase ${SIGNER_ADDRESS}
      --miner.gasprice 10
      --unlock ${SIGNER_ADDRESS} --password password.txt
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
      # --authrpc.port="8552"
    networks:
      priv-eth-net:

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28