version: '3.7'

services:
  geth-bootnode:
    hostname: geth-bootnode
    image: ethereum/client-go:alltools-latest
    volumes:
      - ./bootnode.key:/root/.ethereum/bootnode.key
      - ./genesis.json:/root/genesis.json
    entrypoint: sh -c 'geth init 
      /root/genesis.json && geth  
      --nodekeyhex="840aa8ee27c40d01936f7c6dc433ee32f93a067fdd49aeb753a11e4d7dda80eb"
      --networkid=8000
      --netrestrict="172.16.255.0/24"
      --port=30305'
    networks:
      priv-eth-net-8000:
        ipv4_address: 172.16.255.35

  geth-rpc-endpoint:
    hostname: geth-rpc-endpoint
    image: ethereum/client-go:alltools-latest
    volumes:
      - ./genesis.json:/root/genesis.json
    depends_on:
      - geth-bootnode
    networks:
      priv-eth-net-8000:
        ipv4_address: 172.16.255.155
    ports:
      - "8670:8545"
    entrypoint: sh -c 'geth init 
      /root/genesis.json && geth     
      --netrestrict="172.16.255.0/24"    
      --bootnodes="enode://3d44c3de3080f327ec5248cc721132dd5d6fb645ced8bdcfc54ab2c7b59d65a8b62008f501166985f371b816482f54d8fd7121153af5d581b1e266ecafa27f59@172.16.255.35:0?discport=30305"
      --nat "extip:172.16.255.155"
      --networkid=8000
      --http 
      --http.addr "0.0.0.0" 
      --http.port 8545 
      --http.corsdomain "*" 
      --http.api "admin,clique,eth,debug,miner,net,txpool,personal,web3"'

  geth-miner:
    hostname: geth-miner
    image: ethereum/client-go:alltools-latest
    volumes:
      - ./genesis.json:/root/genesis.json
      - ./pwd.txt:/root/.ethereum/pwd.sec
      - ./keystore:/root/.ethereum/keystore
    depends_on:
      - geth-bootnode
    networks:
      priv-eth-net-8000:
        ipv4_address: 172.16.255.79
    entrypoint: sh -c 'geth init 
      /root/genesis.json && geth   
      --nat "extip:172.16.255.79"
      --netrestrict="172.16.255.0/24"
      --bootnodes="enode://3d44c3de3080f327ec5248cc721132dd5d6fb645ced8bdcfc54ab2c7b59d65a8b62008f501166985f371b816482f54d8fd7121153af5d581b1e266ecafa27f59@172.16.255.35:0?discport=30305"
      --miner.etherbase 0xc18727daB5Fe77C472137437E8955d96D4DB9407   
      --mine  
      --unlock 0xc18727daB5Fe77C472137437E8955d96D4DB9407
      --password /root/.ethereum/pwd.sec'
  nodo-1:
    hostname: nodo-1
    image: ethereum/client-go:alltools-latest
    volumes:
      - ./genesis.json:/root/genesis.json
    depends_on:
      - geth-bootnode
    networks:
      priv-eth-net-8000:
        ipv4_address: 172.16.255.143
    entrypoint: sh -c 'geth init
      /root/genesis.json && geth
      --bootnodes="enode://3d44c3de3080f327ec5248cc721132dd5d6fb645ced8bdcfc54ab2c7b59d65a8b62008f501166985f371b816482f54d8fd7121153af5d581b1e266ecafa27f59@172.16.255.35:0?discport=30305"
      --netrestrict="172.16.255.0/24"
      --nat "extip:172.16.255.143"'
  nodo-2:
    hostname: nodo-2
    image: ethereum/client-go:alltools-latest
    volumes:
      - ./genesis.json:/root/genesis.json
    depends_on:
      - geth-bootnode
    networks:
      priv-eth-net-8000:
        ipv4_address: 172.16.255.27
    entrypoint: sh -c 'geth init
      /root/genesis.json && geth
      --bootnodes="enode://3d44c3de3080f327ec5248cc721132dd5d6fb645ced8bdcfc54ab2c7b59d65a8b62008f501166985f371b816482f54d8fd7121153af5d581b1e266ecafa27f59@172.16.255.35:0?discport=30305"
      --netrestrict="172.16.255.0/24"
      --nat "extip:172.16.255.27"'
  nodo-3:
    hostname: nodo-3
    image: ethereum/client-go:alltools-latest
    volumes:
      - ./genesis.json:/root/genesis.json
    depends_on:
      - geth-bootnode
    networks:
      priv-eth-net-8000:
        ipv4_address: 172.16.255.71
    entrypoint: sh -c 'geth init
      /root/genesis.json && geth
      --bootnodes="enode://3d44c3de3080f327ec5248cc721132dd5d6fb645ced8bdcfc54ab2c7b59d65a8b62008f501166985f371b816482f54d8fd7121153af5d581b1e266ecafa27f59@172.16.255.35:0?discport=30305"
      --netrestrict="172.16.255.0/24"
      --nat "extip:172.16.255.71"'
  nodo-4:
    hostname: nodo-4
    image: ethereum/client-go:alltools-latest
    volumes:
      - ./genesis.json:/root/genesis.json
    depends_on:
      - geth-bootnode
    networks:
      priv-eth-net-8000:
        ipv4_address: 172.16.255.167
    entrypoint: sh -c 'geth init
      /root/genesis.json && geth
      --bootnodes="enode://3d44c3de3080f327ec5248cc721132dd5d6fb645ced8bdcfc54ab2c7b59d65a8b62008f501166985f371b816482f54d8fd7121153af5d581b1e266ecafa27f59@172.16.255.35:0?discport=30305"
      --netrestrict="172.16.255.0/24"
      --nat "extip:172.16.255.167"'
networks:
  priv-eth-net-8000:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.255.0/24
      
