version: '3.7'

services:
  geth-bootnode:
    hostname: geth-bootnode
    env_file:
      - .env
    image: geth-client
    volumes:
      - ./datos/bootnode.key:/root/.ethereum/bootnode.key
    build:
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    command:
      --nodekeyhex="3028ae0069d9089ccae13c5e6731e4a9a480d5d88a80c0aa5ce77b87845abfe8"
      --ipcdisable
      --networkid=${CHAIN_ID}
      --netrestrict="${SUBNET}"
      --port=${NETWORK_PORT}
    networks:
      - priv-eth-net
    entrypoint: sh -c 'geth init /root/genesis.json && geth'

  geth-rpc-endpoint:
    hostname: geth-rpc-endpoint
    env_file:
      - .env
    image: geth-client
    volumes:
      - ./rpc:/root/.ethereum
      - ./genesis.json:/root/genesis.json
    build:
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    depends_on:
      - geth-bootnode    
    command:
      --bootnodes="enode://14e57d66fc357d34b4ad8d9c548dd7e680601f3fe4a56a675cd6604fec0e50ce9f4ffae664afb563c73a86f52b17ba7a459b3f439398b2b417bde294b69f6832@172.16.238.20:30305"
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,txpool,clique,personal"
      --http.corsdomain="*"
      --networkid=${CHAIN_ID}
      --netrestrict="${SUBNET}"
    ports:
      - "${IPRPC}:8545"
    networks:
      - priv-eth-net
    entrypoint: sh -c 'geth init /root/genesis.json && geth'
  
  geth-miner:
    hostname: geth-miner
    env_file:
      - .env
    image: geth-client
    volumes:
      - ./miner:/root/.ethereum
      - ./genesis.json:/root/genesis.json
      - ./password.txt:/root/.ethereum/password.sec
      - ./miner-accounts/keystore:/root/.ethereum/keystore
    build:
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://14e57d66fc357d34b4ad8d9c548dd7e680601f3fe4a56a675cd6604fec0e50ce9f4ffae664afb563c73a86f52b17ba7a459b3f439398b2b417bde294b69f6832@172.16.238.20:30305"
      --mine
      --miner.etherbase ${SIGNER_ADDRESS}
      --unlock ${SIGNER_ADDRESS} --password password.txt
      --networkid=${CHAIN_ID}
      --netrestrict="${SUBNET}"
    networks:
      - priv-eth-net
    entrypoint: sh -c 'geth init /root/genesis.json && geth'

  # Create additional nodes based on NODE_COUNT
  geth-nodo1:
    hostname: geth-nodo1
    image: geth-client
    env_file:
      - .env
    command:
      --bootnodes=enode://14e57d66fc357d34b4ad8d9c548dd7e680601f3fe4a56a675cd6604fec0e50ce9f4ffae664afb563c73a86f52b17ba7a459b3f439398b2b417bde294b69f6832@172.16.238.20:30305
      --allow-insecure-unlock
      --networkid=${CHAIN_ID}
      --netrestrict=172.16.254.0/28

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
